-- Auto-generated by DMS — do not edit manually

hl.monitor({ output = "", mode = "preferred", position = "0x0", scale = 1 })
hl.monitor({ output = "Virtual-1", mode = "3840x2160@59.940", position = "0x0", scale = 1.6, vrr = 0 })
