-- Auto-generated by DMS — do not edit manually

hl.monitor({ output = "", mode = "preferred", position = "0x0", scale = 1 })
hl.monitor({ output = "DP-1", mode = "3840x2160@119.880", position = "0x0", scale = 1.5, vrr = 1 })
