version: "2"

run:
  timeout: 5m
  tests: true

linters:
  default: standard
  enable:
    - bodyclose
    - errcheck
    - errorlint
    - gosec
    - govet
    - ineffassign
    - misspell
    - nilerr
    - nolintlint
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace

  exclusions:
    generated: lax
    presets:
      - comments
      - std-error-handling
